name: Web Scraper

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:

  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        node-version: 16
        
    - uses: actions/setup-python@v2
      with:
        node-version: 16
        
    - name: Install dependencies  
      run: |
        pip install selenium beautifulsoup4
        
    - name: Run script
      env:
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  
      run: python script.py
